opam-version: "2.0"
version: "0.1"
synopsis: "Flatc code generator with OCaml backend"
description:
  "Builds the flatc code generator with the OCaml code generation backend from source. Requires cmake and a C++ compiler."
maintainer: ["Vladimir Silyaev <thecbah@gmail.com>"]
authors: ["Vladimir Silyaev"]
license: "Apache-2.0"
tags: ["flatbuffers" "serialization" "codegen" "ocaml"]
homepage: "https://github.com/TheCBaH/flatbuffers"
bug-reports: "https://github.com/TheCBaH/flatbuffers/issues"
dev-repo: "git+https://github.com/TheCBaH/flatbuffers.git"
extra-source "flatbuffers.tar.gz" {
  src:
    "https://github.com/google/flatbuffers/archive/5761d6e67af841d15ee21bc1ce9a78ffa9cf939e.tar.gz"
  checksum: [
    "sha256=96f209eec2bd4d730729ec67f03b4f94e3febb977324543cd698d78f4250d2cf"
  ]
}
depexts: [
  ["cmake" "g++"] {os-family = "debian"}
  ["cmake" "gcc-c++"] {os-family = "fedora"}
  ["cmake"] {os = "macos"}
]
build: [
  [make "flatc"]
]
install: [
  ["install" "-m" "755" "flatc.ocaml" "%{bin}%/flatc.ocaml"]
]
