opam-version: "2.0"
version: "0.1"
synopsis: "Flatc code generator with OCaml backend"
description:
  "Builds the flatc code generator with the OCaml code generation backend from source. Requires cmake and a C++ compiler."
maintainer: ["Vladimir Silyaev <thecbah@gmail.com>"]
authors: ["Vladimir Silyaev"]
license: "Apache-2.0"
tags: ["flatbuffers" "serialization" "codegen" "ocaml"]
homepage: "https://github.com/TheCBaH/flatbuffers"
bug-reports: "https://github.com/TheCBaH/flatbuffers/issues"
dev-repo: "git+https://github.com/TheCBaH/flatbuffers.git"
extra-source "flatbuffers.tar.gz" {
  src:
    "https://github.com/google/flatbuffers/archive/81edeb17d9118143f2c81caf27edfb0df401279e.tar.gz"
  checksum: [
    "sha256=6ee8a1c2b66990ffcb14130f04ed6ed3982765088c1ca67b74ef66ae43c227bd"
  ]
}
depexts: [
  ["cmake" "g++"] {os-family = "debian"}
  ["cmake" "gcc-c++"] {os-family = "fedora"}
  ["cmake"] {os = "macos"}
]
build: [
  [make "flatc"]
]
install: [
  ["install" "-m" "755" "flatc.ocaml" "%{bin}%/flatc.ocaml"]
]
