opam-version: "2.0"
version: "0.1"
synopsis: "Flatc code generator with OCaml backend"
description:
  "Builds the flatc code generator with the OCaml code generation backend from source. Requires cmake and a C++ compiler."
maintainer: ["Vladimir Silyaev <thecbah@gmail.com>"]
authors: ["Vladimir Silyaev"]
license: "Apache-2.0"
tags: ["flatbuffers" "serialization" "codegen" "ocaml"]
homepage: "https://github.com/TheCBaH/flatbuffers"
bug-reports: "https://github.com/TheCBaH/flatbuffers/issues"
dev-repo: "git+https://github.com/TheCBaH/flatbuffers.git"
extra-source "flatbuffers.tar.gz" {
  src:
    "https://github.com/google/flatbuffers/archive/b8431fbcd7a5c71817f314e18b332c0648554efa.tar.gz"
  checksum: [
    "sha256=760de2b282abe5e7c79472a173530b5662038dd053b0779cd0dd5f78f24f1a0b"
  ]
}
depexts: [
  ["cmake" "g++"] {os-family = "debian"}
  ["cmake" "gcc-c++"] {os-family = "fedora"}
  ["cmake"] {os = "macos"}
]
build: [
  [make "flatc"]
]
install: [
  ["install" "-m" "755" "flatc.ocaml" "%{bin}%/flatc.ocaml"]
]
